### ISSUE TITLE
Improve Android code quality

### ISSUE THREAD

**Issue by edeckers** [edeckers/react-native-blob-courier#38]
- [x] Ensure it offers the exact same functionality the iOS code base 
- [x] Separate download parameter validation (#82)
- [x] Split managed unmanaged download (#81)
- [x] Untangle parameter verification (#80)
- [x] Separation of concerns (#78, #79)
- [x] Simplify threaded tests (#104)
- [x] Reduce code duplication in tests (#104)
- [x] Clean cut between native and React domain (#98)
- [x] More specific error codes (#103)
